# Generated by Django 5.2.17 on 2026-08-31 21:10

import care.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Organization administrator'), ('director', 'Clinical director'), ('therapist', 'Physical therapist'), ('assistant', 'PTA / therapy assistant'), ('scheduler', 'Scheduler / front desk'), ('biller', 'Billing specialist'), ('compliance', 'Compliance officer'), ('patient', 'Patient portal user')], default='therapist', max_length=24)),
                ('credential', models.CharField(blank=True, max_length=64)),
                ('must_use_mfa', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='care.organization')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('evaluation', 'Initial evaluation'), ('follow_up', 'Follow-up visit'), ('progress', 'Progress visit'), ('discharge', 'Discharge visit'), ('telehealth', 'Telehealth')], default='follow_up', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('checked_in', 'Checked in'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], default='scheduled', max_length=16)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=180)),
                ('is_home_visit', models.BooleanField(default=False)),
                ('private_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_type', models.CharField(choices=[('evaluation', 'Initial evaluation'), ('daily', 'Daily treatment note'), ('progress', 'Progress note'), ('discharge', 'Discharge summary'), ('handoff', 'Handoff summary')], default='daily', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review_required', 'Review required'), ('signed', 'Signed / locked'), ('amended', 'Amended')], default='draft', max_length=20)),
                ('service_date', models.DateField(default=django.utils.timezone.localdate)),
                ('diagnosis_snapshot', models.TextField(blank=True)),
                ('precautions_snapshot', models.TextField(blank=True)),
                ('subjective', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('interventions', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('plan_of_care_start', models.DateField(blank=True, null=True)),
                ('plan_of_care_end', models.DateField(blank=True, null=True)),
                ('frequency_per_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_weeks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reassessment_due', models.DateField(blank=True, null=True)),
                ('signature_name', models.CharField(blank=True, max_length=160)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('finalization_attestation', models.BooleanField(default=False)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_note', to='care.appointment')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-service_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('diagnosis_context', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('patient_instructions', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('instructions', models.TextField()),
                ('dosage', models.CharField(max_length=120)),
                ('precaution_note', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('home_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='care.homeprogram')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NoteAddendum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=240)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='note_addenda', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addenda', to='care.clinicalnote')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_record_number', models.CharField(default=care.models.generate_mrn, editable=False, max_length=24, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=200)),
                ('diagnoses', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discharged', 'Discharged')], default='active', max_length=16)),
                ('assigned_therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='care.organization')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='OutcomeScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measure', models.CharField(choices=[('lefs', 'LEFS'), ('odi', 'ODI'), ('ndi', 'NDI'), ('quickdash', 'QuickDASH'), ('tug', 'Timed Up and Go'), ('berg', 'Berg Balance Scale'), ('psfs', 'Patient-Specific Functional Scale')], max_length=20)),
                ('measured_on', models.DateField(default=django.utils.timezone.localdate)),
                ('score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('maximum_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('item_responses', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome_scores', to='care.clinicalnote')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_outcomes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcomes', to='care.patient')),
            ],
            options={
                'ordering': ['measure', 'measured_on'],
            },
        ),
        migrations.CreateModel(
            name='IntakeSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_version', models.CharField(max_length=40)),
                ('answers', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('started', 'Started'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='started', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_intakes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intakes', to='care.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='homeprogram',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_programs', to='care.patient'),
        ),
        migrations.CreateModel(
            name='FunctionalGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('functional_limitation', models.TextField()),
                ('functional_task', models.CharField(max_length=240)),
                ('baseline_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('unit', models.CharField(max_length=64)),
                ('measurement_method', models.CharField(max_length=160)),
                ('target_date', models.DateField()),
                ('suggested_wording', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft / needs approval'), ('active', 'Active'), ('met', 'Met'), ('discontinued', 'Discontinued')], default='draft', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_goals', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_goals', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='care.patient')),
            ],
            options={
                'ordering': ['status', 'target_date'],
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('treatment', 'Consent to treatment'), ('telehealth', 'Telehealth consent'), ('financial', 'Financial policy'), ('voice', 'Voice documentation consent'), ('privacy', 'Privacy notice acknowledgement')], max_length=24)),
                ('document_version', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('signed', 'Signed'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='signed', max_length=16)),
                ('signature_name', models.CharField(blank=True, max_length=160)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_consents', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='care.patient')),
            ],
            options={
                'ordering': ['-signed_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='care.patient'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=80)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='care.organization')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='care.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='care.patient'),
        ),
        migrations.CreateModel(
            name='AIArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('progress', 'Progress-note draft'), ('discharge', 'Discharge-summary draft'), ('handoff', 'Handoff-summary draft'), ('goal', 'Goal suggestion'), ('hep', 'Home-program suggestion'), ('patient_summary', 'Patient visit summary'), ('compliance', 'Compliance check')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft — therapist review required'), ('approved', 'Approved by therapist'), ('rejected', 'Rejected'), ('applied', 'Applied to editable note')], default='draft', max_length=16)),
                ('source_note_ids', models.JSONField(default=list)),
                ('source_fingerprint', models.CharField(max_length=128)),
                ('provider', models.CharField(default='local-template', max_length=80)),
                ('model_version', models.CharField(default='clinical-draft-v1', max_length=80)),
                ('draft_text', models.TextField()),
                ('safety_notice', models.TextField(default='Draft only. A licensed therapist must verify, edit, approve, and sign.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_ai_artifacts', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_artifacts', to=settings.AUTH_USER_MODEL)),
                ('applied_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_artifacts', to='care.clinicalnote')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_artifacts', to='care.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecureMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='care.patient')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_secure_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_secure_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Superbill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_date', models.DateField()),
                ('codes', models.JSONField(default=list)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for billing'), ('submitted', 'Submitted'), ('paid', 'Paid')], default='draft', max_length=16)),
                ('payment_processor_reference', models.CharField(blank=True, max_length=160)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='superbills', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='superbills', to='care.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoiceCapture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_confirmed', models.BooleanField(default=False)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('transcript', models.TextField()),
                ('status', models.CharField(choices=[('transcribed', 'Transcript ready for review'), ('reviewed', 'Transcript reviewed'), ('discarded', 'Discarded')], default='transcribed', max_length=16)),
                ('linked_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_captures', to='care.clinicalnote')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voice_captures', to='care.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voice_captures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['organization', 'last_name', 'first_name'], name='care_patien_organiz_567dea_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['organization', 'medical_record_number'], name='care_patien_organiz_1facbf_idx'),
        ),
        migrations.AddIndex(
            model_name='outcomescore',
            index=models.Index(fields=['patient', 'measure', 'measured_on'], name='care_outcom_patient_d91313_idx'),
        ),
        migrations.AddConstraint(
            model_name='outcomescore',
            constraint=models.UniqueConstraint(fields=('patient', 'measure', 'measured_on'), name='unique_outcome_per_patient_measure_day'),
        ),
        migrations.AddIndex(
            model_name='functionalgoal',
            index=models.Index(fields=['patient', 'status', 'target_date'], name='care_functi_patient_4c5ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['patient', 'service_date'], name='care_clinic_patient_f36644_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['therapist', 'service_date'], name='care_clinic_therapi_75d7e1_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['status', 'reassessment_due'], name='care_clinic_status_8ff074_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organization', '-created_at'], name='care_audite_organiz_2d6a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['patient', '-created_at'], name='care_audite_patient_df1faa_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['therapist', 'starts_at'], name='care_appoin_therapi_efd0b8_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'starts_at'], name='care_appoin_patient_134614_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='appointment_ends_after_start'),
        ),
        migrations.AddIndex(
            model_name='aiartifact',
            index=models.Index(fields=['patient', 'kind', 'status'], name='care_aiarti_patient_64d954_idx'),
        ),
        migrations.AddIndex(
            model_name='securemessage',
            index=models.Index(fields=['recipient', 'read_at'], name='care_secure_recipie_930024_idx'),
        ),
    ]
