# Generated by Django 5.2.17 on 2026-09-01 23:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0004_feature_subscriptionplan_organizationsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('address_line_1', models.CharField(blank=True, max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('timezone', models.CharField(default='America/Los_Angeles', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='care.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('specialty', models.CharField(blank=True, max_length=120)),
                ('credentials', models.CharField(blank=True, max_length=120)),
                ('license_number', models.CharField(blank=True, max_length=80)),
                ('npi_number', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('locations', models.ManyToManyField(blank=True, related_name='providers', to='care.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='care.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['organization', 'name'], name='care_locati_organiz_71143f_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['organization', 'last_name', 'first_name'], name='care_provid_organiz_074799_idx'),
        ),
    ]
