# Generated by Django 5.2.17 on 2026-09-01 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0005_location_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='location_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='care.location'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='care.provider'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['provider', 'starts_at'], name='care_appoin_provide_290673_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['location_detail', 'starts_at'], name='care_appoin_locatio_2eee05_idx'),
        ),
    ]
