# Generated by Django 5.2.17 on 2026-09-03 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0006_appointment_location_detail_appointment_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='organization',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organization',
            name='client_number',
            field=models.PositiveBigIntegerField(default=1000, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(default='United States', max_length=80),
        ),
        migrations.AddField(
            model_name='organization',
            name='portal_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_tier',
            field=models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='starter', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='suspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='suspension_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='America/New_York', max_length=64),
        ),
        migrations.AddField(
            model_name='organization',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super administrator'), ('admin', 'Organization administrator'), ('director', 'Clinical director'), ('therapist', 'Physical therapist'), ('assistant', 'PTA / therapy assistant'), ('scheduler', 'Scheduler / front desk'), ('biller', 'Billing specialist'), ('compliance', 'Compliance officer'), ('patient', 'Patient portal user')], default='therapist', max_length=24),
        ),
    ]
