# Generated by Django 5.2.17 on 2026-09-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0007_organization_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='client_number',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
