# Generated by Django 5.2.17 on 2026-09-03 17:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_client_number_sequence(apps, schema_editor):
    Organization = apps.get_model("care", "Organization")
    Sequence = apps.get_model("care", "ClientNumberSequence")
    maximum = Organization.objects.exclude(client_number__isnull=True).order_by("-client_number").values_list("client_number", flat=True).first()
    Sequence.objects.create(pk=1, next_number=max(maximum or 999, 999) + 1)


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0008_alter_organization_client_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNumberSequence',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('next_number', models.PositiveBigIntegerField(default=1000)),
            ],
        ),
        migrations.RunPython(seed_client_number_sequence, migrations.RunPython.noop),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClientInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='care.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
