# Generated by Django 5.2.17 on 2026-09-04 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0014_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='care.appointmenttype'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='booking_source',
            field=models.CharField(choices=[('front_desk', 'Front desk'), ('patient_portal', 'Patient portal'), ('public_booking', 'Public booking page'), ('provider', 'Provider'), ('mobile_app', 'Mobile app')], default='front_desk', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason_for_visit',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='appointmenttype',
            name='buffer_after_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointmenttype',
            name='buffer_before_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointmenttype',
            name='default_kind',
            field=models.CharField(blank=True, help_text='Optional Appointment.Kind value this maps to for clinical-workflow defaults.', max_length=20),
        ),
        migrations.AddField(
            model_name='appointmenttype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointmenttype',
            name='online_booking_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appointmenttype',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='appointmenttype',
            name='requires_new_patient',
            field=models.BooleanField(default=False, help_text='Only offered to patients booking as a new patient (e.g. Initial Evaluation).'),
        ),
        migrations.AddField(
            model_name='provider',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='online_booking_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='BookingConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('online_booking_enabled', models.BooleanField(default=False)),
                ('allow_new_patients', models.BooleanField(default=True)),
                ('allow_returning_patients', models.BooleanField(default=True)),
                ('allow_any_available_therapist', models.BooleanField(default=True)),
                ('min_notice_hours', models.PositiveSmallIntegerField(default=4)),
                ('max_advance_days', models.PositiveSmallIntegerField(default=90)),
                ('slot_interval_minutes', models.PositiveSmallIntegerField(default=15)),
                ('cancellation_policy', models.TextField(blank=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_configuration', to='care.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationClosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('reason', models.CharField(max_length=160)),
                ('active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='care.location')),
            ],
            options={
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['location', 'start_datetime', 'end_datetime'], name='care_locati_locatio_8eb0ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProviderAppointmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('custom_duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('appointment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_links', to='care.appointmenttype')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_type_links', to='care.provider')),
            ],
            options={
                'ordering': ['appointment_type__name'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'appointment_type'), name='unique_provider_appointment_type')],
            },
        ),
        migrations.CreateModel(
            name='ProviderAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_availabilities', to='care.location')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='care.provider')),
            ],
            options={
                'ordering': ['provider', 'day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['provider', 'location', 'day_of_week'], name='care_provid_provide_5cb6fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProviderTimeOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('reason', models.CharField(choices=[('vacation', 'Vacation'), ('personal', 'Personal leave'), ('conference', 'Conference'), ('lunch', 'Lunch'), ('meeting', 'Meeting'), ('admin', 'Admin time'), ('other', 'Other')], default='other', max_length=16)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('cancelled', 'Cancelled')], default='approved', max_length=16)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_time_off', to='care.location')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='care.provider')),
            ],
            options={
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['provider', 'start_datetime', 'end_datetime'], name='care_provid_provide_7562ae_idx')],
            },
        ),
    ]
