# Generated by Django 5.2.17 on 2026-09-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0015_appointment_appointment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
