# Generated by Django 5.2.17 on 2026-09-06 02:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0018_backfill_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('django_session_key', models.CharField(max_length=64, unique=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, choices=[('new_login', 'Signed in from another browser or device'), ('user_logout', 'Signed out'), ('idle_timeout', 'Idle timeout'), ('absolute_timeout', 'Maximum session lifetime reached'), ('password_changed', 'Password changed'), ('password_reset', 'Password reset by an administrator'), ('account_locked', 'Account locked'), ('account_suspended', 'Account suspended'), ('account_deactivated', 'Account deactivated'), ('account_deleted', 'Account deleted'), ('admin_revoked', 'Signed out by an administrator')], max_length=24)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('device_name', models.CharField(blank=True, max_length=80)),
                ('browser_name', models.CharField(blank=True, max_length=80)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='care.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
