# Generated by Django 5.2.17 on 2026-09-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0019_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='license_expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='license_issuing_state',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
