# Generated by Django 5.2.17 on 2026-09-06 17:11

import care.models
import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0020_user_license_expires_at_user_license_issuing_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='license_expires_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='license_issuing_state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='license_number',
        ),
        migrations.CreateModel(
            name='UserLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_number', models.CharField(max_length=80)),
                ('issuing_state', models.CharField(max_length=40)),
                ('license_type', models.CharField(blank=True, max_length=40)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField()),
                ('verification_status', models.CharField(choices=[('pending_verification', 'Pending verification'), ('verified', 'Verified')], default='pending_verification', max_length=24)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\kasam\\Projects\\PhysioTrac360\\private_media'), upload_to=care.models.user_license_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'doc', 'docx'])])),
                ('document_original_filename', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expires_at'],
                'indexes': [models.Index(fields=['user', 'expires_at'], name='care_userli_user_id_e441e8_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'issuing_state', 'license_number'), name='unique_user_license_per_state_number')],
            },
        ),
    ]
