# Generated by Django 5.2.17 on 2026-09-07 02:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0021_user_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='cosign_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='cosigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='cosigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cosigned_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='discharge_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='objective_measurements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='subjective_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='pta_cosign_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clinicalnote',
            name='note_type',
            field=models.CharField(choices=[('evaluation', 'Initial evaluation'), ('daily', 'Daily treatment note'), ('progress', 'Progress note'), ('re_evaluation', 'Re-evaluation'), ('discharge', 'Discharge summary'), ('handoff', 'Handoff summary')], default='daily', max_length=20),
        ),
        migrations.CreateModel(
            name='NoteIntervention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=240)),
                ('body_region', models.CharField(blank=True, max_length=80)),
                ('minutes', models.PositiveSmallIntegerField(default=0)),
                ('units', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_timed', models.BooleanField(default=True)),
                ('patient_response', models.CharField(blank=True, max_length=240)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_items', to='care.clinicalnote')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
