# Generated by Django 5.2.17 on 2026-09-09 21:51

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0023_episodeofcare_appointment_episode_of_care_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_name', models.CharField(blank=True, max_length=160)),
                ('authorization_number', models.CharField(blank=True, max_length=80)),
                ('visits_approved', models.PositiveSmallIntegerField()),
                ('visits_used', models.PositiveSmallIntegerField(default=0)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('expires_at', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('denied', 'Denied'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_authorizations', to=settings.AUTH_USER_MODEL)),
                ('episode_of_care', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorizations', to='care.episodeofcare')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='care.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='care.patient')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='authorization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='care.authorization'),
        ),
        migrations.AddIndex(
            model_name='authorization',
            index=models.Index(fields=['organization', 'patient', 'status'], name='care_author_organiz_0d242c_idx'),
        ),
    ]
