# Generated by Django 5.2.17 on 2026-09-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0024_authorization_appointment_authorization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteintervention',
            name='category',
            field=models.CharField(blank=True, choices=[('therapeutic_exercise', 'Therapeutic Exercise'), ('manual_therapy', 'Manual Therapy'), ('therapeutic_activity', 'Therapeutic Activity'), ('neuromuscular_reeducation', 'Neuromuscular Re-education'), ('gait_training', 'Gait Training'), ('self_care', 'Self-care / Home Management'), ('patient_education', 'Patient Education'), ('other', 'Other Intervention')], max_length=32),
        ),
        migrations.AlterField(
            model_name='aiartifact',
            name='kind',
            field=models.CharField(choices=[('progress', 'Progress-note draft'), ('discharge', 'Discharge-summary draft'), ('handoff', 'Handoff-summary draft'), ('goal', 'Goal suggestion'), ('hep', 'Home-program suggestion'), ('patient_summary', 'Patient visit summary'), ('compliance', 'Compliance check'), ('coding', 'Coding suggestion')], max_length=32),
        ),
    ]
