# Generated by Django 5.2.17 on 2026-09-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0025_noteintervention_category_alter_aiartifact_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiartifact',
            name='sections',
            field=models.JSONField(blank=True, default=list, help_text='Optional per-section breakdown of draft_text for granular therapist review: [{key, label, draftText, status, reviewedText}, ...]. Empty for kinds that are only ever reviewed as a single block.'),
        ),
    ]
