# Generated by Django 5.2.17 on 2026-09-10 00:22

import care.models
import django.core.files.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0026_aiartifact_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('payer_id', models.CharField(blank=True, max_length=40)),
                ('electronic_payer_id', models.CharField(blank=True, max_length=40)),
                ('address_line_1', models.CharField(blank=True, max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('timely_filing_days', models.PositiveSmallIntegerField(default=90)),
                ('authorization_required', models.BooleanField(default=False)),
                ('authorization_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payers', to='care.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatientInsurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')], default='primary', max_length=16)),
                ('plan_name', models.CharField(blank=True, max_length=160)),
                ('member_id', models.CharField(max_length=80)),
                ('group_number', models.CharField(blank=True, max_length=80)),
                ('subscriber_name', models.CharField(blank=True, max_length=160)),
                ('subscriber_date_of_birth', models.DateField(blank=True, null=True)),
                ('relationship_to_subscriber', models.CharField(choices=[('self', 'Self'), ('spouse', 'Spouse'), ('child', 'Child'), ('other', 'Other')], default='self', max_length=16)),
                ('effective_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('copay', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('coinsurance_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('deductible', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('authorization_required', models.BooleanField(default=False)),
                ('card_front', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\kasam\\Projects\\PhysioTrac360\\private_media'), upload_to=care.models.patient_insurance_card_upload_path)),
                ('card_back', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\kasam\\Projects\\PhysioTrac360\\private_media'), upload_to=care.models.patient_insurance_card_upload_path)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patient_insurance_policies', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_insurance_policies', to='care.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_policies', to='care.patient')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_policies', to='care.payer')),
            ],
            options={
                'ordering': ['rank', '-effective_date'],
            },
        ),
        migrations.AddIndex(
            model_name='payer',
            index=models.Index(fields=['organization', 'name'], name='care_payer_organiz_cf41d4_idx'),
        ),
        migrations.AddIndex(
            model_name='patientinsurance',
            index=models.Index(fields=['organization', 'patient', 'rank'], name='care_patien_organiz_75471c_idx'),
        ),
    ]
