# Generated by Django 5.2.17 on 2026-09-10 00:24

import care.models
import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0027_payer_patientinsurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinsurance',
            name='card_back',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\kasam\\Projects\\PhysioTrac360\\private_media'), upload_to=care.models.patient_insurance_card_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='card_front',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\kasam\\Projects\\PhysioTrac360\\private_media'), upload_to=care.models.patient_insurance_card_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
