# Generated by Django 5.2.17 on 2026-09-10 01:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0028_alter_patientinsurance_card_back_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('is_billable', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_date', models.DateField()),
                ('cpt_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Enter a 5-character CPT/HCPCS code (e.g. 97110).', regex='^[A-Z0-9]{5}$')])),
                ('modifiers', models.JSONField(blank=True, default=list)),
                ('units', models.PositiveSmallIntegerField(default=1)),
                ('minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recommended_units', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('units_override_reason', models.TextField(blank=True)),
                ('charge_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready to bill'), ('billed', 'Billed'), ('void', 'Void')], default='draft', max_length=16)),
                ('clinical_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='care.clinicalnote')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_charges', to=settings.AUTH_USER_MODEL)),
                ('episode_of_care', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='care.episodeofcare')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='care.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='care.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='care.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendered_charges', to=settings.AUTH_USER_MODEL)),
                ('diagnosis_codes', models.ManyToManyField(blank=True, related_name='charges', to='care.diagnosiscode')),
            ],
            options={
                'ordering': ['-service_date', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'patient', 'service_date'], name='care_charge_organiz_2cecd1_idx')],
            },
        ),
    ]
