# Generated by Django 5.2.17 on 2026-09-10 02:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0029_diagnosiscode_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='npi_number',
            field=models.CharField(blank=True, help_text='Billing-provider (group) NPI — CMS-1500 box 33.', max_length=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Federal tax ID / EIN — CMS-1500 box 25.', max_length=20),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis_code_list', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('validation_error', 'Validation Error'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('denied', 'Denied'), ('partial_payment', 'Partial Payment'), ('paid', 'Paid'), ('appealed', 'Appealed'), ('corrected', 'Corrected'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('clearinghouse_claim_id', models.CharField(blank=True, max_length=80)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_claims', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='care.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='care.patient')),
                ('patient_insurance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='care.patientinsurance')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='care.payer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='charge',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='care.claim'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['organization', 'patient', 'status'], name='care_claim_organiz_bd2d2b_idx'),
        ),
    ]
