# Generated by Django 5.2.17 on 2026-09-10 13:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0030_organization_npi_number_organization_tax_id_claim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('insurance_payment', 'Insurance Payment'), ('patient_payment', 'Patient Payment'), ('adjustment', 'Contractual Adjustment'), ('write_off', 'Write-off'), ('refund', 'Refund'), ('transfer', 'Transfer')], max_length=20)),
                ('method', models.CharField(blank=True, choices=[('check', 'Check'), ('eft', 'EFT'), ('credit_card', 'Credit Card'), ('cash', 'Cash'), ('era', 'ERA (Electronic)'), ('other', 'Other')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference', models.CharField(blank=True, max_length=160)),
                ('denial_code', models.CharField(blank=True, max_length=20)),
                ('denial_reason', models.CharField(blank=True, max_length=240)),
                ('notes', models.TextField(blank=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='care.claim')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_transactions', to='care.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_transactions', to='care.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_claim_transactions', to=settings.AUTH_USER_MODEL)),
                ('transferred_to_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='care.claim')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'patient', 'payment_date'], name='care_claimt_organiz_ca7378_idx'), models.Index(fields=['claim'], name='care_claimt_claim_i_963232_idx')],
            },
        ),
    ]
