# Generated by Django 5.2.17 on 2026-09-10 14:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0031_claimtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='superbill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='care.superbill'),
        ),
        migrations.CreateModel(
            name='CashPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('package', 'Visit Package'), ('membership', 'Membership')], max_length=16)),
                ('name', models.CharField(max_length=160)),
                ('visits_included', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('visits_used', models.PositiveSmallIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('purchased_on', models.DateField(default=django.utils.timezone.localdate)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cash_packages', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_packages', to='care.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_packages', to='care.patient')),
            ],
            options={
                'ordering': ['-purchased_on'],
                'indexes': [models.Index(fields=['organization', 'patient', 'status'], name='care_cashpa_organiz_e65f81_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClaimDenial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('denial_code', models.CharField(blank=True, max_length=20)),
                ('denial_reason', models.CharField(max_length=240)),
                ('denied_on', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('action_notes', models.TextField(blank=True)),
                ('appeal_status', models.CharField(choices=[('not_appealed', 'Not Appealed'), ('preparing', 'Preparing Appeal'), ('submitted', 'Appeal Submitted'), ('won', 'Appeal Won'), ('lost', 'Appeal Lost')], default='not_appealed', max_length=16)),
                ('resolution', models.CharField(choices=[('open', 'Open'), ('resolved_paid', 'Resolved — Paid'), ('resolved_written_off', 'Resolved — Written Off'), ('resolved_patient_billed', 'Resolved — Billed to Patient')], default='open', max_length=24)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denials', to='care.claim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_denials', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_denials', to='care.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_denials', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_denials', to='care.patient')),
            ],
            options={
                'ordering': ['resolution', 'due_date', '-denied_on'],
                'indexes': [models.Index(fields=['organization', 'resolution', 'due_date'], name='care_claimd_organiz_9955f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statement_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField()),
                ('balance_at_generation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_statements', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_statements', to='care.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='care.patient')),
            ],
            options={
                'ordering': ['-statement_date'],
                'indexes': [models.Index(fields=['organization', 'patient', '-statement_date'], name='care_patien_organiz_c3bc9d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpt_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Enter a 5-character CPT/HCPCS code (e.g. 97110).', regex='^[A-Z0-9]{5}$')])),
                ('label', models.CharField(max_length=160)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_prices', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_prices', to='care.organization')),
            ],
            options={
                'ordering': ['cpt_code'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'cpt_code'), name='unique_service_price_per_org_cpt')],
            },
        ),
    ]
