# Generated by Django 5.2.17 on 2026-09-10 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0032_charge_superbill_cashpackage_claimdenial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='portal_user',
            field=models.OneToOneField(blank=True, help_text="The login identity (role=patient) this chart's portal account uses, if one has been issued.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
