# Generated by Django 5.2.17 on 2026-09-10 19:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0035_formtemplate_formsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeexercise',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to an instructional video (YouTube, Vimeo, or similar).'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='visible_to_patient',
            field=models.BooleanField(default=False, help_text="Off by default for a staff upload — a clinician must explicitly share a document before the portal can show it. A patient's own upload through the portal always sets this true at creation."),
        ),
        migrations.CreateModel(
            name='HomeExerciseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pain_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('difficulty_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('home_exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='care.homeexercise')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_exercise_logs', to='care.patient')),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['patient', '-completed_at'], name='care_homeex_patient_a29e7f_idx')],
            },
        ),
    ]
