# Generated by Django 5.2.17 on 2026-09-10 19:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0036_homeexercise_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securemessage',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('appointment', 'Appointment'), ('hep', 'Home exercise program'), ('billing', 'Billing'), ('clinical', 'Clinical')], default='general', max_length=16),
        ),
        migrations.CreateModel(
            name='OutcomeAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measure', models.CharField(choices=[('lefs', 'LEFS'), ('odi', 'ODI'), ('ndi', 'NDI'), ('quickdash', 'QuickDASH'), ('tug', 'Timed Up and Go'), ('berg', 'Berg Balance Scale'), ('psfs', 'Patient-Specific Functional Scale')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=16)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_outcome_measures', to=settings.AUTH_USER_MODEL)),
                ('completed_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='care.outcomescore')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcome_assignments', to='care.patient')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='care_outcom_patient_f2aa6b_idx')],
            },
        ),
    ]
