# Generated by Django 5.2.17 on 2026-09-10 20:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0037_securemessage_category_outcomeassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('processor_reference', models.CharField(blank=True, max_length=160)),
                ('failure_message', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_payments', to='care.patient')),
            ],
            options={
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['patient', '-attempted_at'], name='care_patien_patient_7fa30f_idx')],
            },
        ),
    ]
