# Generated by Django 5.2.17 on 2026-09-10 20:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0038_patientpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text="Whether this patient receives the (content-free) 'you have a new secure message' email."),
        ),
        migrations.AddField(
            model_name='patient',
            name='pharmacy_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pharmacy_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='patient',
            name='pharmacy_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone call'), ('sms', 'Text message')], default='email', max_length=16),
        ),
        migrations.CreateModel(
            name='PatientProfileChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Proposed {field_name: new_value}, keys restricted to ALLOWED_FIELDS.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_note', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_change_requests', to='care.patient')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_profile_changes', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_profile_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='care_patien_patient_05042d_idx')],
            },
        ),
    ]
