# Generated by Django 5.2.17 on 2026-09-11 13:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0039_patient_email_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_areas', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_areas', to='care.organization')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='care.provider')),
            ],
            options={
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAreaZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Enter a 5-digit ZIP code.', regex='^\\d{5}$')])),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_codes', to='care.servicearea')),
            ],
            options={
                'ordering': ['zip_code'],
            },
        ),
        migrations.CreateModel(
            name='MobileCareRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('scheduled', 'Scheduled'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('source', models.CharField(choices=[('patient_portal', 'Patient portal'), ('front_desk', 'Front desk')], default='front_desk', max_length=16)),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=80)),
                ('zip_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Enter a 5-digit ZIP code.', regex='^\\d{5}$')])),
                ('reason_for_visit', models.CharField(blank=True, max_length=240)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('earliest_date', models.DateField()),
                ('latest_date', models.DateField(blank=True, null=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_care_request', to='care.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mobile_care_requests', to=settings.AUTH_USER_MODEL)),
                ('episode_of_care', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_care_requests', to='care.episodeofcare')),
                ('matched_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_mobile_care_requests', to='care.provider')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobile_care_requests', to='care.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobile_care_requests', to='care.patient')),
                ('preferred_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_mobile_care_requests', to='care.provider')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='care_mobile_organiz_412961_idx'), models.Index(fields=['organization', 'zip_code'], name='care_mobile_organiz_7ea9d4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='servicearea',
            index=models.Index(fields=['organization', 'provider', 'is_active'], name='care_servic_organiz_e59207_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceareazipcode',
            index=models.Index(fields=['zip_code'], name='care_servic_zip_cod_92f7e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceareazipcode',
            constraint=models.UniqueConstraint(fields=('service_area', 'zip_code'), name='unique_zip_per_service_area'),
        ),
    ]
