# Generated by Django 5.2.17 on 2026-09-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0040_mobile_care_service_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilecarerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matching', 'Matching'), ('provider_offered', 'Offered to provider'), ('matched', 'Matched'), ('accepted', 'Accepted'), ('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=16),
        ),
    ]
