# Generated by Django 5.2.17 on 2026-09-11 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0041_mobile_care_request_status_expand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveSmallIntegerField(default=1, help_text='1 = best match; supports offering candidates in order.')),
                ('match_reason', models.CharField(choices=[('zip_coverage', 'ZIP coverage'), ('continuity', 'Continuity of care'), ('manual', 'Manual override')], default='zip_coverage', max_length=16)),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='offered', max_length=16)),
                ('offered_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=240)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_matches', to='care.organization')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_matches', to='care.provider')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='care.mobilecarerequest')),
            ],
            options={
                'ordering': ['service_request', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='HomeVisitAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('en_route', 'En route'), ('arrived', 'Arrived'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='offered', max_length=16)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('en_route_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=240)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_visit_assignment', to='care.appointment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_visit_assignments', to='care.organization')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_visit_assignments', to='care.provider')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='care.mobilecarerequest')),
                ('provider_match', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='assignment', to='care.providermatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='providermatch',
            index=models.Index(fields=['organization', 'service_request', 'status'], name='care_provid_organiz_d5faf1_idx'),
        ),
        migrations.AddIndex(
            model_name='providermatch',
            index=models.Index(fields=['provider', 'status'], name='care_provid_provide_367321_idx'),
        ),
        migrations.AddConstraint(
            model_name='providermatch',
            constraint=models.UniqueConstraint(fields=('service_request', 'provider'), name='unique_provider_match_per_request'),
        ),
        migrations.AddIndex(
            model_name='homevisitassignment',
            index=models.Index(fields=['organization', 'provider', 'status'], name='care_homevi_organiz_d69c00_idx'),
        ),
        migrations.AddIndex(
            model_name='homevisitassignment',
            index=models.Index(fields=['service_request'], name='care_homevi_service_f18a6e_idx'),
        ),
    ]
