# Generated by Django 5.2.17 on 2026-09-11 15:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0042_provider_match_home_visit_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitTravelStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('en_route', 'En route'), ('arrived', 'Arrived'), ('delayed', 'Delayed')], max_length=16)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_log', to='care.homevisitassignment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assignment', '-created_at'], name='care_visitt_assignm_15bfa8_idx')],
            },
        ),
    ]
