# Generated by Django 5.2.17 on 2026-09-11 15:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0043_visit_travel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='location_sharing_enabled',
            field=models.BooleanField(default=False, help_text="Explicit opt-in for live GPS location capture during a home-visit assignment's travel segment. Off by default — enabling this is a separate, deliberate action from account/employment consent."),
        ),
        migrations.CreateModel(
            name='ProviderLocationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='care.homevisitassignment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assignment', '-created_at'], name='care_provid_assignm_fefc32_idx'), models.Index(fields=['created_at'], name='care_provid_created_c0989a_idx')],
            },
        ),
    ]
