# Generated by Django 5.2.17 on 2026-09-11 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0044_provider_location_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='homevisitassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_home_visit_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homevisitassignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_home_visit_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobilecarerequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_mobile_care_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providermatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_provider_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providermatch',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_provider_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_service_areas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visittravelstatus',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visit_travel_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='homevisitassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['offered', 'accepted', 'en_route', 'arrived', 'in_progress'])), fields=('service_request',), name='unique_active_assignment_per_request'),
        ),
        migrations.AddConstraint(
            model_name='servicearea',
            constraint=models.UniqueConstraint(fields=('provider', 'name'), name='unique_service_area_name_per_provider'),
        ),
    ]
