# Generated by Django 5.2.17 on 2026-09-11 16:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0045_mobile_care_audit_fields_and_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVisitAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability_type', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('blocked', 'Blocked')], default='available', max_length=16)),
                ('is_recurring', models.BooleanField(default=True, help_text='Recurring: applies every `day_of_week`. One-time: applies only on `specific_date`.')),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Required when is_recurring is set; ignored for a one-time entry.', null=True)),
                ('specific_date', models.DateField(blank=True, help_text='Required when is_recurring is not set; ignored for a recurring entry.', null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_home_visit_availabilities', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_visit_availabilities', to='care.organization')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_visit_availabilities', to='care.provider')),
                ('service_area', models.ForeignKey(blank=True, help_text="Optional — the region this window applies to, if it differs from the provider's general coverage.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_visit_availabilities', to='care.servicearea')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_home_visit_availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', 'is_recurring', 'day_of_week', 'specific_date', 'start_time'],
                'indexes': [models.Index(fields=['organization', 'provider', 'is_active'], name='care_homevi_organiz_a53332_idx'), models.Index(fields=['provider', 'day_of_week'], name='care_homevi_provide_071598_idx'), models.Index(fields=['provider', 'specific_date'], name='care_homevi_provide_bf9a13_idx')],
            },
        ),
    ]
