# Generated by Django 5.2.17 on 2026-09-11 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0046_home_visit_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='max_travel_distance_miles',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='primary_zip_code',
            field=models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Enter a 5-digit ZIP code.', regex='^\\d{5}$')]),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='radius_miles',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='state',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
