# Generated by Django 5.2.17 on 2026-09-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0047_service_area_geographic_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilecarerequest',
            name='home_access_notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mobilecarerequest',
            name='is_new_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobilecarerequest',
            name='mobility_notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mobilecarerequest',
            name='payment_method',
            field=models.CharField(choices=[('insurance', 'Insurance'), ('self_pay', 'Self-pay')], default='insurance', max_length=16),
        ),
        migrations.AddField(
            model_name='mobilecarerequest',
            name='preferred_time_window',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (8am–12pm)'), ('afternoon', 'Afternoon (12pm–5pm)'), ('evening', 'Evening (5pm–9pm)'), ('any', 'Any time')], max_length=16),
        ),
        migrations.AddField(
            model_name='mobilecarerequest',
            name='primary_condition',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='mobilecarerequest',
            name='provider_gender_preference',
            field=models.CharField(choices=[('no_preference', 'No preference'), ('male', 'Male'), ('female', 'Female')], default='no_preference', max_length=16),
        ),
        migrations.AddField(
            model_name='mobilecarerequest',
            name='requested_service',
            field=models.CharField(blank=True, choices=[('evaluation', 'Initial evaluation'), ('follow_up', 'Follow-up visit'), ('progress', 'Progress visit'), ('discharge', 'Discharge visit')], max_length=20),
        ),
        migrations.AddField(
            model_name='mobilecarerequest',
            name='specialty_requested',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='mobilecarerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Requested'), ('matching', 'Matching'), ('provider_offered', 'Offered to provider'), ('matched', 'Matched'), ('accepted', 'Accepted'), ('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=16),
        ),
    ]
