# Generated by Django 5.2.17 on 2026-09-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0048_mobile_care_request_detail_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='providermatch',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0-100 weighted match score at the time this candidate was ranked — see care.mobile_care.score_provider_match(). Null for a match created outside the ranking pipeline (e.g. a future manual override).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='providermatch',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Sub-scores (continuity/specialty/availability/distance/preference/caseload) and human-readable reasons behind `score` — staff/admin display only, never exposed to the patient portal.'),
        ),
        migrations.AlterField(
            model_name='providermatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('offered', 'Offered'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=16),
        ),
    ]
