# Generated by Django 5.2.17 on 2026-09-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0049_provider_match_scoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='providermatch',
            name='viewed_at',
            field=models.DateTimeField(blank=True, help_text='When the offered provider first opened this offer — see care.mobile_care.mark_offer_viewed().', null=True),
        ),
    ]
