# Generated by Django 5.2.17 on 2026-09-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0050_provider_match_offer_viewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodeofcare',
            name='condition',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='episodeofcare',
            name='expected_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episodeofcare',
            name='expected_visit_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episodeofcare',
            name='visit_frequency',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
