# Generated by Django 5.2.17 on 2026-09-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0051_care_episode_mobile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='homevisitassignment',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homevisitassignment',
            name='status',
            field=models.CharField(choices=[('offered', 'Offered'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('scheduled', 'Scheduled'), ('en_route', 'En route'), ('arrived', 'Arrived'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='offered', max_length=16),
        ),
    ]
