# Generated by Django 5.2.17 on 2026-09-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0052_home_visit_assignment_scheduled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='home_visit_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='clinicalnote',
            name='note_type',
            field=models.CharField(choices=[('evaluation', 'Initial evaluation'), ('daily', 'Daily treatment note'), ('soap', 'SOAP note'), ('home_visit', 'Home visit note'), ('progress', 'Progress note'), ('re_evaluation', 'Re-evaluation'), ('discharge', 'Discharge summary'), ('handoff', 'Handoff summary')], default='daily', max_length=20),
        ),
    ]
