# Generated by Django 5.2.17 on 2026-09-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0053_clinical_note_home_visit_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=False, help_text='Opt-in for Mobile Care text message updates (visit reminders, provider en route, etc.). Off by default, unlike email — SMS consent is opt-in, not opt-out. No effect until an SMS provider is actually configured (see care/mobile_care_notifications.py).'),
        ),
    ]
