# Generated by Django 5.2.17 on 2026-09-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0054_patient_sms_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilecarerequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='mobilecarerequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
