# Generated by Django 5.2.17 on 2026-09-12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('care', '0055_geocoded_coordinates_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderLocationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('arrived', 'Provider arrived'), ('cancelled', 'Visit cancelled'), ('stopped_by_provider', 'Provider turned off location sharing'), ('timed_out', 'Session left open too long')], max_length=24)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_sessions', to='care.homevisitassignment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_location_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='providerlocationsnapshot',
            name='care_provid_assignm_fefc32_idx',
        ),
        migrations.RemoveField(
            model_name='providerlocationsnapshot',
            name='assignment',
        ),
        migrations.AddField(
            model_name='providerlocationsnapshot',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pings', to='care.providerlocationsession'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='providerlocationsession',
            index=models.Index(fields=['assignment', 'ended_at'], name='care_provid_assignm_d69b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='providerlocationsnapshot',
            index=models.Index(fields=['session', '-created_at'], name='care_provid_session_85a876_idx'),
        ),
    ]
