# Generated by Django 5.2.17 on 2026-09-12 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0056_provider_location_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientpayment',
            name='mobile_care_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_payments', to='care.mobilecarerequest'),
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='home_visit_kind',
            field=models.CharField(blank=True, choices=[('evaluation', 'Initial evaluation'), ('follow_up', 'Follow-up visit'), ('progress', 'Progress visit'), ('discharge', 'Discharge visit'), ('telehealth', 'Telehealth')], max_length=16),
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='is_home_visit_travel_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mobilecarerequest',
            name='payment_method',
            field=models.CharField(choices=[('insurance', 'Insurance'), ('self_pay', 'Self-pay'), ('package', 'Package/Membership')], default='insurance', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='serviceprice',
            constraint=models.UniqueConstraint(condition=models.Q(('home_visit_kind', ''), _negated=True), fields=('organization', 'home_visit_kind'), name='unique_home_visit_kind_price_per_org'),
        ),
        migrations.AddConstraint(
            model_name='serviceprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_home_visit_travel_fee', True)), fields=('organization',), name='unique_home_visit_travel_fee_per_org'),
        ),
    ]
