# Generated by Django 5.2.17 on 2026-09-12 02:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0057_mobile_care_billing_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileCareConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile_care_enabled', models.BooleanField(default=False)),
                ('default_visit_duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('available_services', models.JSONField(blank=True, default=list)),
                ('allowed_provider_roles', models.JSONField(blank=True, default=list)),
                ('max_travel_radius_miles', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('offer_expiration_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('patient_cancellation_window_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('provider_cancellation_notice_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('provider_cancellation_requires_reason', models.BooleanField(default=True)),
                ('same_provider_continuity_preferred', models.BooleanField(blank=True, null=True)),
                ('match_weight_overrides', models.JSONField(blank=True, default=dict)),
                ('service_hours_start', models.TimeField(blank=True, null=True)),
                ('service_hours_end', models.TimeField(blank=True, null=True)),
                ('disabled_notification_events', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mobile_care_configurations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_care_configuration', to='care.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_mobile_care_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MobileCarePlatformDefaults',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_visit_duration_minutes', models.PositiveSmallIntegerField(default=45)),
                ('offer_expiration_hours', models.PositiveSmallIntegerField(default=4)),
                ('patient_cancellation_window_hours', models.PositiveSmallIntegerField(default=24)),
                ('provider_cancellation_notice_hours', models.PositiveSmallIntegerField(default=4)),
                ('max_travel_radius_miles', models.PositiveSmallIntegerField(default=25)),
                ('same_provider_continuity_preferred', models.BooleanField(default=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_mobile_care_platform_defaults', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
