# Generated by Django 5.2.17 on 2026-09-12 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0058_mobile_care_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='care.organization'),
        ),
    ]
