# Generated by Django 5.2.17 on 2026-09-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0059_audit_event_nullable_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilecareconfiguration',
            name='mobile_care_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
