from django.urls import path

from .. import views as legacy_views
from . import admin_config, documents, note_views, public_booking, user_licenses, views, workflow_views, super_admin


urlpatterns = [
    path("public/organizations/<slug:slug>/", public_booking.public_organization_detail, name="api-public-organization"),
    path("public/organizations/<slug:slug>/locations/", public_booking.public_locations, name="api-public-locations"),
    path("public/organizations/<slug:slug>/appointment-types/", public_booking.public_appointment_types, name="api-public-appointment-types"),
    path("public/organizations/<slug:slug>/providers/", public_booking.public_providers, name="api-public-providers"),
    path("public/organizations/<slug:slug>/availability/", public_booking.public_availability, name="api-public-availability"),
    path("public/bookings/", public_booking.public_create_booking, name="api-public-bookings"),
    path("auth/csrf/", views.csrf, name="api-csrf"),
    path("auth/facility/", views.facility, name="api-facility"),
    path("auth/login/", views.login, name="api-login"),
    path("auth/logout/", views.logout, name="api-logout"),
    path("auth/change-password/", views.change_password, name="api-change-password"),
    path("auth/me/", views.me, name="api-me"),
    path("auth/sessions/", views.my_sessions, name="api-my-sessions"),
    path("auth/sessions/<uuid:session_id>/revoke/", views.revoke_my_session, name="api-revoke-my-session"),
    path("auth/sessions/revoke-others/", views.revoke_my_other_sessions, name="api-revoke-my-other-sessions"),
    path("dashboard/", views.dashboard, name="api-dashboard"),
    path("users/", views.organization_users, name="api-org-users"),
    path("users/<uuid:user_id>/", views.organization_user_detail, name="api-org-user-detail"),
    path("users/<uuid:user_id>/status-action/", views.organization_user_status_action, name="api-org-user-status-action"),
    path("users/<uuid:user_id>/revoke-sessions/", views.organization_user_revoke_sessions, name="api-org-user-revoke-sessions"),
    path("users/<uuid:user_id>/licenses/", user_licenses.organization_user_licenses, name="api-org-user-licenses"),
    path(
        "users/<uuid:user_id>/licenses/<uuid:license_id>/",
        user_licenses.organization_user_license_detail,
        name="api-org-user-license-detail",
    ),
    path(
        "users/<uuid:user_id>/licenses/<uuid:license_id>/document/",
        user_licenses.organization_user_license_document,
        name="api-org-user-license-document",
    ),
    path(
        "users/<uuid:user_id>/licenses/<uuid:license_id>/verify/",
        user_licenses.organization_user_license_verify,
        name="api-org-user-license-verify",
    ),
    path("patients/", views.patients, name="api-patients"),
    path("staff/", views.staff_options, name="api-staff-options"),
    path("locations/", admin_config.locations, name="api-locations"),
    path("locations/<uuid:location_id>/", admin_config.location_detail, name="api-location-detail"),
    path("appointment-types/", admin_config.appointment_types, name="api-appointment-types"),
    path("appointment-types/<uuid:appointment_type_id>/", admin_config.appointment_type_detail, name="api-appointment-type-detail"),
    path("reports/operations/", admin_config.operational_report, name="api-operational-report"),
    path("patients/<uuid:patient_id>/", views.patient_detail, name="api-patient-detail"),
    path("patients/<uuid:patient_id>/edit/", views.patient_for_edit, name="api-patient-for-edit"),
    path("patients/<uuid:patient_id>/documents/", documents.patient_documents, name="api-patient-documents"),
    path(
        "patients/<uuid:patient_id>/documents/<uuid:document_id>/download/",
        documents.patient_document_download,
        name="api-patient-document-download",
    ),
    path(
        "patients/<uuid:patient_id>/workspace/",
        workflow_views.patient_workspace,
        name="api-patient-workspace",
    ),
    path(
        "patients/<uuid:patient_id>/timeline/",
        workflow_views.patient_timeline,
        name="api-patient-timeline",
    ),
    path("documentation/", note_views.documentation_list, name="api-documentation-list"),
    path("patients/<uuid:patient_id>/notes/", note_views.note_create, name="api-note-create"),
    path("notes/<uuid:note_id>/", note_views.note_detail, name="api-note-detail"),
    path("notes/<uuid:note_id>/sign/", note_views.note_sign, name="api-note-sign"),
    path("notes/<uuid:note_id>/cosign/", note_views.note_cosign, name="api-note-cosign"),
    path("notes/<uuid:note_id>/addenda/", note_views.addendum_create, name="api-note-addendum-create"),
    path(
        "notes/<uuid:note_id>/interventions/",
        note_views.interventions_replace,
        name="api-note-interventions-replace",
    ),
    path(
        "patients/<uuid:patient_id>/drafts/",
        workflow_views.draft_create,
        name="api-draft-create",
    ),
    path("drafts/<uuid:artifact_id>/review/", workflow_views.artifact_review, name="api-draft-review"),
    path(
        "patients/<uuid:patient_id>/goal-suggestions/",
        workflow_views.goal_suggestions,
        name="api-goal-suggestions",
    ),
    path("patients/<uuid:patient_id>/goals/", workflow_views.goal_create, name="api-goal-create"),
    path("goals/<uuid:goal_id>/approve/", workflow_views.goal_approve, name="api-goal-approve"),
    path(
        "patients/<uuid:patient_id>/outcomes/",
        workflow_views.outcome_create,
        name="api-outcome-create",
    ),
    path(
        "patients/<uuid:patient_id>/voice-captures/",
        workflow_views.voice_capture_create,
        name="api-voice-capture-create",
    ),
    path(
        "voice-captures/<uuid:capture_id>/create-note/",
        workflow_views.voice_capture_create_note,
        name="api-voice-capture-create-note",
    ),
    path(
        "patients/<uuid:patient_id>/home-program-suggestions/",
        workflow_views.home_program_suggestion_list,
        name="api-home-program-suggestions",
    ),
    path(
        "patients/<uuid:patient_id>/home-programs/",
        workflow_views.home_program_create,
        name="api-home-program-create",
    ),
    path(
        "home-programs/<uuid:program_id>/approve/",
        workflow_views.home_program_approve,
        name="api-home-program-approve",
    ),
    path(
        "patients/<uuid:patient_id>/intakes/",
        workflow_views.intake_create,
        name="api-intake-create",
    ),
    path(
        "patients/<uuid:patient_id>/consents/",
        workflow_views.consent_create,
        name="api-consent-create",
    ),
    path(
        "patients/<uuid:patient_id>/referrals/",
        workflow_views.referral_create,
        name="api-referral-create",
    ),
    path(
        "referrals/<uuid:referral_id>/status/",
        workflow_views.referral_status_update,
        name="api-referral-status-update",
    ),
    path(
        "patients/<uuid:patient_id>/messages/",
        workflow_views.secure_message_create,
        name="api-secure-message-create",
    ),
    path(
        "patients/<uuid:patient_id>/superbills/",
        workflow_views.superbill_create,
        name="api-superbill-create",
    ),
    path(
        "patients/<uuid:patient_id>/payments/",
        workflow_views.payment_create,
        name="api-payment-create",
    ),
    path(
        "patients/<uuid:patient_id>/appointments/",
        workflow_views.appointment_create,
        name="api-appointment-create",
    ),
    path("schedule/", views.schedule, name="api-schedule"),
    path(
        "appointments/<uuid:appointment_id>/move/",
        legacy_views.appointment_move,
        name="api-appointment-move",
    ),
    path("audit-events/", workflow_views.audit_events, name="api-audit-events"),
    path("super-admin/clients/", super_admin.clients, name="api-super-admin-clients"),
    path("super-admin/users/", super_admin.all_users, name="api-super-admin-users"),
    path("super-admin/users/<uuid:user_id>/", super_admin.user_detail, name="api-super-admin-user-detail"),
    path("super-admin/users/<uuid:user_id>/status-action/", super_admin.user_status_action, name="api-super-admin-user-status-action"),
    path("super-admin/users/<uuid:user_id>/revoke-sessions/", super_admin.user_revoke_sessions, name="api-super-admin-user-revoke-sessions"),
    path("super-admin/users/<uuid:user_id>/licenses/", user_licenses.super_admin_user_licenses, name="api-super-admin-user-licenses"),
    path(
        "super-admin/users/<uuid:user_id>/licenses/<uuid:license_id>/",
        user_licenses.super_admin_user_license_detail,
        name="api-super-admin-user-license-detail",
    ),
    path(
        "super-admin/users/<uuid:user_id>/licenses/<uuid:license_id>/document/",
        user_licenses.super_admin_user_license_document,
        name="api-super-admin-user-license-document",
    ),
    path(
        "super-admin/users/<uuid:user_id>/licenses/<uuid:license_id>/verify/",
        user_licenses.super_admin_user_license_verify,
        name="api-super-admin-user-license-verify",
    ),
    path("super-admin/clients/create/", super_admin.client_create, name="api-super-admin-client-create"),
    path("super-admin/clients/<int:client_number>/", super_admin.client_detail, name="api-super-admin-client-detail"),
    path("super-admin/clients/<int:client_number>/users/", super_admin.client_users, name="api-super-admin-client-users"),
    path("super-admin/clients/<int:client_number>/audit-events/", super_admin.client_audit_events, name="api-super-admin-client-audit-events"),
    path("super-admin/clients/<int:client_number>/privileged-access/", super_admin.privileged_access_grants, name="api-super-admin-privileged-access"),
    path("super-admin/clients/<int:client_number>/privileged-access/<uuid:grant_id>/revoke/", super_admin.privileged_access_revoke, name="api-super-admin-privileged-access-revoke"),
    path("super-admin/clients/<int:client_number>/privileged-patients/", super_admin.privileged_patients, name="api-super-admin-privileged-patients"),
    path("super-admin/clients/<int:client_number>/privileged-patients/<uuid:patient_id>/", super_admin.privileged_patient_detail, name="api-super-admin-privileged-patient-detail"),
    path("super-admin/clients/<int:client_number>/admin/resend-invite/", super_admin.resend_admin_invitation, name="api-super-admin-client-admin-resend-invite"),
    path("super-admin/clients/<int:client_number>/<str:action>/", super_admin.client_status, name="api-super-admin-client-status"),
    path("auth/activate-invitation/", super_admin.activate_invitation, name="api-activate-invitation"),
]
